version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: awesomedatabase
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
